// Google Material Symbols (Rounded, weight 400), imported as React SVG components via vite-plugin-svgr.

export { default as CloseIcon } from '@material-symbols/svg-400/rounded/close.svg?react'
export { default as ChevronDownIcon } from '@material-symbols/svg-400/rounded/keyboard_arrow_down.svg?react'
export { default as ChevronUpIcon } from '@material-symbols/svg-400/rounded/keyboard_arrow_up.svg?react'
export { default as ChevronLeftIcon } from '@material-symbols/svg-400/rounded/keyboard_arrow_left.svg?react'
export { default as ChevronRightIcon } from '@material-symbols/svg-400/rounded/keyboard_arrow_right.svg?react'
export { default as CheckIcon } from '@material-symbols/svg-400/rounded/check.svg?react'
export { default as ChatIcon } from '@material-symbols/svg-400/rounded/chat_bubble.svg?react'
export { default as DashboardIcon } from '@material-symbols/svg-400/rounded/space_dashboard.svg?react'
export { default as LightModeIcon } from '@material-symbols/svg-400/rounded/light_mode.svg?react'
export { default as DarkModeIcon } from '@material-symbols/svg-400/rounded/dark_mode.svg?react'
export { default as SystemModeIcon } from '@material-symbols/svg-400/rounded/desktop_windows.svg?react'
export { default as ArrowUpIcon } from '@material-symbols/svg-400/rounded/arrow_upward.svg?react'
export { default as ArrowDownIcon } from '@material-symbols/svg-400/rounded/arrow_downward.svg?react'
export { default as SortIcon } from '@material-symbols/svg-400/rounded/unfold_more.svg?react'
export { default as NewChatIcon } from '@material-symbols/svg-400/rounded/edit_square.svg?react'
export { default as SearchIcon } from '@material-symbols/svg-400/rounded/search.svg?react'
export { default as OpenInNewIcon } from '@material-symbols/svg-400/rounded/open_in_new.svg?react'
export { default as WorkIcon } from '@material-symbols/svg-400/rounded/work.svg?react'
export { default as CompanyIcon } from '@material-symbols/svg-400/rounded/apartment.svg?react'
export { default as LocationIcon } from '@material-symbols/svg-400/rounded/location_on.svg?react'
export { default as ScheduleIcon } from '@material-symbols/svg-400/rounded/schedule.svg?react'
export { default as CategoryIcon } from '@material-symbols/svg-400/rounded/category.svg?react'
export { default as StopIcon } from '@material-symbols/svg-400/rounded/stop_circle.svg?react'
export { default as TrendingUpIcon } from '@material-symbols/svg-400/rounded/trending_up.svg?react'
export { default as BoltIcon } from '@material-symbols/svg-400/rounded/bolt.svg?react'
export { default as ClearFilterIcon } from '@material-symbols/svg-400/rounded/filter_alt_off.svg?react'
